# ⚙️ Implementasi Kalkulator Matriks Interaktif dengan NumPy di Python

Berikut adalah skrip Python yang mengimplementasikan kalkulator matriks:

* **Mengimpor NumPy:** Menggunakan library `numpy` untuk operasi matematika matriks yang efisien.
* **Fungsi `get_matrix()`:** Meminta pengguna untuk memasukkan dimensi dan elemen-elemen matriks, dengan validasi sederhana untuk memastikan jumlah kolom sesuai. Mengembalikan matriks NumPy.
* **Fungsi `matrix_operations(A, B)`:** Menerima dua matriks (A dan B) sebagai input dan melakukan berbagai operasi:
    * Penjumlahan, Pengurangan, dan Perkalian Element-wise dengan penanganan `ValueError` jika dimensi tidak sesuai.
    * Dot Product dengan penanganan `ValueError` jika dimensi tidak sesuai.
    * Menghitung dan menampilkan transpose dari kedua matriks.
    * Menghitung dan menampilkan determinan dan invers dari Matriks A dengan penanganan `np.linalg.LinAlgError` jika matriks tidak persegi atau tidak invertible.
* **Fungsi `main()`:** Fungsi utama program yang memanggil `get_matrix()` untuk mendapatkan input matriks dari pengguna dan kemudian memanggil `matrix_operations()` untuk melakukan perhitungan.
* **Blok `if __name__ == "__main__":`:** Memastikan fungsi `main()` hanya dijalankan ketika skrip dieksekusi secara langsung.

Jalankan sel kode di bawah untuk melakukan perhitungan matriksmu!

In [6]:
import numpy as np

# Function to Get Matrix Input
def get_matrix():
    try:
        rows = int(input("Enter the number of rows: "))
        cols = int(input("Enter the number of columns: "))
        print("Enter the matrix elements row by row:")
        elements = []
        for _ in range(rows):
            row = list(map(float, input().split()))
            if len(row) != cols:
                raise ValueError("Number of columns doesn't match.")
            elements.append(row)
        return np.array(elements)
    except ValueError as e:
        print("Error:", e)
        return None

# Matrix Operations
def matrix_operations(A, B):
    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)

    try:
        print("\nAddition:\n", A + B)
    except ValueError:
        print("\nAddition: Matrices must have the same dimensions.")

    try:
        print("\nSubtraction:\n", A - B)
    except ValueError:
        print("\nSubtraction: Matrices must have the same dimensions.")

    try:
        print("\nElement-wise Multiplication:\n", A * B)
    except ValueError:
        print("\nElement-wise Multiplication: Matrices must have the same dimensions.")

    try:
        print("\nDot Product:\n", np.dot(A, B))
    except ValueError:
        print("\nDot Product: Number of columns in A must equal the number of rows in B.")

    print("\nTranspose of A:\n", A.T)
    print("\nTranspose of B:\n", B.T)

    try:
        print("\nDeterminant of A:", np.linalg.det(A))
    except np.linalg.LinAlgError:
        print("\nDeterminant of A: Not applicable (Matrix must be square).")

    try:
        print("\nInverse of A:\n", np.linalg.inv(A))
    except np.linalg.LinAlgError:
        print("\nInverse of A: Not invertible.")

# Main Program
def main():
    print("Matrix Calculator")
    print("=================")
    print("Input Matrix A:")
    A = get_matrix()
    if A is None:
        return

    print("\nInput Matrix B:")
    B = get_matrix()
    if B is None:
        return

    matrix_operations(A, B)

if __name__ == "__main__":
    main()

Matrix Calculator
Input Matrix A:


Enter the number of rows:  2
Enter the number of columns:  2


Enter the matrix elements row by row:


 1 2
 3 4



Input Matrix B:


Enter the number of rows:  2
Enter the number of columns:  2


Enter the matrix elements row by row:


 5 6
 7 8



Matrix A:
 [[1. 2.]
 [3. 4.]]

Matrix B:
 [[5. 6.]
 [7. 8.]]

Addition:
 [[ 6.  8.]
 [10. 12.]]

Subtraction:
 [[-4. -4.]
 [-4. -4.]]

Element-wise Multiplication:
 [[ 5. 12.]
 [21. 32.]]

Dot Product:
 [[19. 22.]
 [43. 50.]]

Transpose of A:
 [[1. 3.]
 [2. 4.]]

Transpose of B:
 [[5. 7.]
 [6. 8.]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
